### ISSUE TITLE
Roadmap of this project?

### ISSUE THREAD

**Issue by TommyLike** [rpm-rs/rpm#26] opened 2022-11-22 14:16 UTC
Will more features be supported in the future? which features are on the list and when will be supported? Do we have a roadmap?

**Comment by cmeister2** [comment] 2022-11-22 14:47
Speaking personally, I'd love to introduce some code which allows extraction of header metadata without requiring the whole file to be parsed. I used to have that in `fez` and it'd be great to be official.

**Comment by cmeister2** [comment] 2022-11-22 14:56
> > Speaking personally, I'd love to introduce some code which allows extraction of header metadata without requiring the whole file to be parsed. I used to have that in `fez` and it'd be great to be official.
> 
> @cmeister2  what's the benefit we can get by such changes considering the rpm file is already downloaded and present on local machine.

I mean that's definitely not true? My package `remote-package` supports reading package metadata from remote RPM and DEB files - because metadata is at the start of the file you can download a very small set of data to be able to get it. With the stock `rpm-rs` I was getting times of minutes to download and parse a 300MB RPM, with `fez` it was milliseconds.

**Comment by TommyLike** [comment] 2022-11-22 15:05
@cmeister2 that's sound interesting, also your idea sound like the stargz concept used in the OCI image, btw, considering the metadata of rpm file, I thought they would all appear in the repo db file.

**Comment by TommyLike** [comment] 2022-11-23 00:28
> > @cmeister2 that's sound interesting, also your idea sound like the stargz concept used in the OCI image, btw, considering the metadata of rpm file, I thought they would all appear in the repo db file.
> 
> Unfortunately not all RPMs are being stored in repos... (hence why I need the functionality 😂)

Thanks, @cmeister2  then one more question, what't the usecase of remote package, analysis ingredient  of the package(SCA). lazy loading the package binary?

**Comment by cmeister2** [comment] 2022-11-23 07:24
> Thanks, @cmeister2  then one more question, what't the usecase of remote package, analysis ingredient  of the package(SCA). lazy loading the package binary?

Not sure this is quite the right place for this discussion (maybe a wiki would be better?), but it's so I can compare two remote packages (one archived, one in a repo) and only download the package if it's not been archived already. It's easier to compare package metadata than anything else.

The reason I want it is to get feature parity with `deb-pkg` basically!

**Comment by ximon18** [comment] 2022-11-23 19:41
On the roadmap topic, I use cargo-generate-rpm and a while ago raised https://github.com/cat-in-136/cargo-generate-rpm/issues/20, which according to the owner requires rpm-rs enhancements to resolve the issue.

In summary the issue is that RPMs produced by cargo-generate-rpm fail rpmlint checking. One such issue  (e.g. `BuildHost` which [rpmlint raises an error for if missing](https://github.com/rpm-software-management/rpmlint/blob/742749c0c05e784304b560e4463565d922f903ab/rpmlint/checks/TagsCheck.py#L510)) and there doesn't appear to be an rpm-rs API to set those tags.

However, I'm now wondering should I submit a PR to rpm-rs, or here (or to fez)? Until cargo-generate-rpm switches to use this crate any PR raised here won't solve the problem, so this now also becomes a question of should cargo-generate-rpm update to use this crate instead of the original rpm-rs?

**Comment by drahnr** [comment] 2022-11-25 08:09
https://github.com/rpm-rs/rpm/discussions/31

**Comment by kczimm** [comment] 2023-01-30 14:31
Any plans on publishing a release soon? I'm still stuck on the old `rpm-rs` crate which now has deps with future incompatibility issues on the new Rust release.

**Comment by drahnr** [comment] 2023-01-30 16:47
@kczimm https://github.com/rpm-rs/rpm/pull/77 should be out soon™

**Comment by dralley** [comment] 2023-03-12 16:47
I'm going to close this, features and bugs should be discussed on an individual basis in filed issues, that way information doesn't get lost

**Closed by dralley** 2023-03-12 16:47 UTC
